# Generated by Django 3.2 on 2023-01-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_add_film_certificate"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="gender",
            field=models.TextField(
                choices=[("male", "male"), ("female", "female")],
                null=True,
                verbose_name="gender",
            ),
        ),
    ]
