# Generated by Django 3.2 on 2023-01-24 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="gender",
        ),
    ]
