# Generated by Django 3.2 on 2023-01-24 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_remove_person_gender"),
    ]

    operations = [
        migrations.RenameField(
            model_name="filmwork",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="filmwork",
            old_name="modified",
            new_name="modified_at",
        ),
        migrations.RenameField(
            model_name="genre",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="genre",
            old_name="modified",
            new_name="modified_at",
        ),
        migrations.RenameField(
            model_name="genrefilmwork",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="person",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="person",
            old_name="modified",
            new_name="modified_at",
        ),
        migrations.RenameField(
            model_name="personfilmwork",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="filmwork",
            name="certificate",
        ),
    ]
